mode = "dark"

accent = "#FFFFFF"
selection = "#FFFFFF"
muted = "#FFFFFF"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#000000"

foreground = "#FFFFFF"
dark_foreground = "#FFFFFF"
light_foreground = "#FFFFFF"
bright_foreground = "#FFFFFF"

hyprland_active_border = "rgba(ffffffff)"
hyprland_inactive_border = "rgba(00000000)"

red = "#FFFFFF"
yellow = "#FFFFFF"
orange = "#FFFFFF"
green = "#FFFFFF"
cyan = "#FFFFFF"
blue = "#FFFFFF"
magenta = "#FFFFFF"
brown = "#000000"

bright_red = "#FFFFFF"
bright_yellow = "#FFFFFF"
bright_green = "#FFFFFF"
bright_cyan = "#FFFFFF"
bright_blue = "#FFFFFF"
bright_magenta = "#FFFFFF"
